### ISSUE TITLE
bitcoinMessage.verify() returns false positives

### ISSUE THREAD

**Issue by iluu** [bitcoinjs/bitcoinjs-message#18]
bitcoinMessage.verify returns a false positive in some cases, see sample below:

```javascript
const bitcoinMessage = require('bitcoinjs-message'); 

var address = '1EauidThcsXuEAXoWxT3DG5D9Y8KvM2CDs';
var invalidSignature = 'AASF4L7Q1nsXn2MzW2uc8apjIARMRCfirsGVhq5ZwA37IxUsurYGyHtU0k/kBmIwWLLUNqitUHPMhZJMFZ5SSnA=';
var validSignature = 'IASF4L7Q1nsXn2MzW2uc8apjIARMRCfirsGVhq5ZwA37IxUsurYGyHtU0k/kBmIwWLLUNqitUHPMhZJMFZ5SSnA=';
var message = '1EauidThcsXuEAXoWxT3DG5D9Y8KvM2CDs:1544454641:starRegistry';

console.log(bitcoinMessage.verify(message, address, validSignature));
console.log(bitcoinMessage.verify(message, address, invalidSignature));

// Returns
// true
// true - should be false ?
```

**Comment by junderw** [comment]
you are modifying the recovery flag to another value that just so happens to recover the same pubkey.

This is not a bug, as no one can modify the actual signature.

**Comment by junderw** [comment]
The recovery flag is basically like a map to tell the verifying app where to look for the proper public key to verify the signature.

technically it is supposed to be within a specific range, to make things easier for app developers.

1. I know of no app that malforms the recovery ID in the way you describe.
2. Malforming the recovery ID, in the worst case scenario, can only invalidate a valid signature. It can not cause an invalid signature to be valid.

So if you were just messing around to see if there are bugs in this library, this is not a critical bug, at most it's a confusing implementation difference between us and others.

But if you actually found an app that generates that malformed signature, that is a bug since it should be a valid recovery ID.

Our library was given a bad coordinate, but it turned out it pointed to the correct pubkey out of luck.

Since the goal is to validate the signature, we ignore the malformed recoveryID.

We could fix it though, so I'll leave this open.

**Comment by iluu** [comment]
I found it by accident while implementing a client app using your library.

And thanks for the explanation :) Appreciated !

**Comment by junderw** [comment]
Fixed the issue:

Your specific example was:

```
# Your valid sig's flag byte was 32 (aka 0x20 in hex)
> (27 + 4 + 1).toString(2) // (check binary)
'100000'
# Your invalid sig's flag byte was 0 ( aka 0x00 )

# "valid" flag bytes all add 27 to them. and only the first 3 bits have meaning.
# so to verify, we subtract 27, then bitwise AND the number to find recovery and compressed info
# Your invalid one is 0, so 0 - 27 is -27
# grab recovery
> (-27 & 3).toString(2)
'1' // 1 is the position of the pubkey
# grab if it is compressed or not
> (-27 & 4).toString(2) // any non-zero == compressed
'100'

# Now look at the valid one
> (5 & 3).toString(2)
'1'
> (5 & 4).toString(2)
'100'
```

Different values were giving the same value on accident, but if the compressed flag or the recovery flag were miscalculated it would only invalidate the valid signature.
