### ISSUE TITLE
Suggestion: Support for empty prefix

### ISSUE THREAD

**Issue by sondreb** [bitcoinjs/bitcoinjs-message#26]
Has it been considered adding support for no message prefix?

The library supports a custom prefix, but it doesn't support no prefix.

**Comment by junderw** [comment]
You can create an empty prefix by passing in `'\u0000'` as the magicPrefix

**Comment by junderw** [comment]
If you mean you want to pass `''` into magicPrefix and have the hash be over messageVISize and message only, then you should use just a normal signature library.

The message signing protocol signs the hash of the following.

`prefixVISize + prefix + messageVISize + message`

The `\u0018` in the Bitcoin default message is VISize === 24 (0x18 in hex is 24)

`Bitcoin Signed Message:\n` is exactly 24 characters.

0 in VI is 0x00, or `\u0000`

So therefore, passing in '\u0000' would be "an empty prefix" for this protocol.

**Comment by sondreb** [comment]
OK thanks, I just did a verification and it did add some bytes with the empty prefix. I'll either continue using a fork I did or as suggested, write another library that is simpler.

**Comment by junderw** [comment]
> write another library that is simpler

Just use the secp256k1 library.

I am having a hard time understanding your goal. This library takes a simple signature from secp256k1 and encodes / verifies it according to the signature protocol in Bitcoin Core (which many altcoins copy pasted over to their clients)

To be honest, this signature protocol is not the best in the world, it's just here to be compatible with bitcoin core and its derivatives.

If you want to create your own signature protocol, the "simpler" option is to just hash the data you want to sign and sign it using secp256k1.

Since this protocol is signing over the message and prefix, and removing the prefix means you are only signing the message.

secp256k1 library provides a function to sign a message, so it is sufficient for your needs.

Unless you need it to be base58 encoded and formatted in a Bitcoin-Core-similar-but-not-compatible way for some reason. Which I wouldn't understand why that is necessary.

If you explain your use case I can help you think of a solution, but I can guarantee "forking this library to remove the prefix" is an inefficient solution to any possible problem you are trying to fix.

**Comment by sondreb** [comment]
Hi, what I meant with "library that is simpler", is just a wrapper around secp256k1 and some other pieces of protocol to make the usage of what I'm working on easier for other devs.

What I'm working on is signing of identities and data, basically a lean implementation of DID / SDS specifications. So it's JSON Web Signatures and soon JSON Web Encryption. I initially relied upon the basic signing method for both .NET and JavaScript, but already don't use the message signing in C# any longer.

It's not easy to get into this field as there are older specifications, competing specifications, evolutions .. JSON-LD Signatures, Proofs, Verifiable Credentials, JOSE... I might migrate to one of the libraries by digitalbazaar, which have various implementations.

Spent countless hours reading specifications / standards recently and almost no coding.

**Comment by junderw** [comment]
> Spent countless hours reading specifications / standards recently and almost no coding.

Cryptography in a nutshell.

Unfortunately, we follow a protocol specified by Bitcoin Core, which requires at least the prefix size set to 0 added onto the beginning of the signed message, so we are probably not the right protocol for you, but you are welcome to use our code as a starting point for some protocol you come up with. Be careful though.

Good luck on your journey.
